"""initial schema: mandates, constraints, carts, cart_items, decisions,
findings, proof_bundles

Revision ID: 0001
Revises:
Create Date: 2026-08-22

Hand-authored (not autogenerated) since this is the first migration and no
live database was available to diff against while this was written — see
apps/api/models/tables.py, which this mirrors column-for-column.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_PORTABLE_JSON = sa.JSON().with_variant(postgresql.JSONB(), "postgresql")


def upgrade() -> None:
    op.create_table(
        "mandates",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("principal_id", sa.String(), nullable=False, index=True),
        sa.Column("agent_id", sa.String(), nullable=False, index=True),
        sa.Column("public_key", sa.String(), nullable=False),
        sa.Column("signature", sa.String(), nullable=False),
        sa.Column("budget_total_paise", sa.BigInteger(), nullable=False),
        sa.Column("budget_used_paise", sa.BigInteger(), nullable=False),
        sa.Column("per_txn_cap_paise", sa.BigInteger(), nullable=False),
        sa.Column("merchant_allowlist", _PORTABLE_JSON, nullable=False),
        sa.Column("category_allowlist", _PORTABLE_JSON, nullable=False),
        sa.Column("velocity_max_txn_per_hour", sa.Integer(), nullable=False),
        sa.Column("velocity_max_txn_per_day", sa.Integer(), nullable=False),
        sa.Column("auto_strip_unrequested", sa.Boolean(), nullable=False),
        sa.Column("intent_text", sa.Text(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.create_table(
        "carts",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column(
            "mandate_id", sa.String(), sa.ForeignKey("mandates.id"), nullable=False, index=True
        ),
        sa.Column("merchant_id", sa.String(), nullable=False, index=True),
        sa.Column("quote_id", sa.String(), nullable=False),
        sa.Column("total_paise", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False, server_default="INR"),
    )

    op.create_table(
        "decisions",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("cart_id", sa.String(), sa.ForeignKey("carts.id"), nullable=False, index=True),
        sa.Column("outcome", sa.String(), nullable=False, index=True),
        sa.Column("reason_code", sa.String(), nullable=False),
        sa.Column("behaviour_score", sa.Float(), nullable=False),
        sa.Column("behaviour_signals", _PORTABLE_JSON, nullable=False),
        sa.Column("stripped_items", _PORTABLE_JSON, nullable=False),
        sa.Column("stage_latencies_ms", _PORTABLE_JSON, nullable=False),
        sa.Column("razorpay_order_id", sa.String(), nullable=True),
        sa.Column("razorpay_payment_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
            index=True,
        ),
    )

    op.create_table(
        "constraints",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column(
            "mandate_id", sa.String(), sa.ForeignKey("mandates.id"), nullable=False, index=True
        ),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("field", sa.String(), nullable=False),
        sa.Column("operator", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("is_deterministic", sa.Boolean(), nullable=False),
        sa.Column("source_span", sa.Text(), nullable=False),
    )

    op.create_table(
        "cart_items",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("cart_id", sa.String(), sa.ForeignKey("carts.id"), nullable=False, index=True),
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("unit_price_paise", sa.BigInteger(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("attributes", _PORTABLE_JSON, nullable=False),
    )

    op.create_table(
        "findings",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column(
            "decision_id", sa.String(), sa.ForeignKey("decisions.id"), nullable=False, index=True
        ),
        sa.Column("constraint_id", sa.String(), nullable=False),
        sa.Column("verdict", sa.String(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("adjudicator", sa.String(), nullable=False),
    )

    op.create_table(
        "proof_bundles",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column(
            "decision_id",
            sa.String(),
            sa.ForeignKey("decisions.id"),
            nullable=False,
            unique=True,
            index=True,
        ),
        sa.Column("prev_hash", sa.Text(), nullable=False),
        sa.Column("payload_hash", sa.Text(), nullable=False, index=True),
        sa.Column("signature", sa.Text(), nullable=False),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", _PORTABLE_JSON, nullable=False),
    )


def downgrade() -> None:
    op.drop_table("proof_bundles")
    op.drop_table("findings")
    op.drop_table("cart_items")
    op.drop_table("constraints")
    op.drop_table("decisions")
    op.drop_table("carts")
    op.drop_table("mandates")
